core/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from core.classes import *
from core.views import *

app_name = 'core'

urlpatterns = [
    path('login/', LogInView.as_view(), name='login'),
    path('logout/', log_out, name='logout'),
    path('offers/', list_offer, name='offer_list'),

    path('offers/create/', create_offer, name='offer_create'),
    path('offers/data_table/', login_required(OfferListJson.as_view()), name='offer_data_table'),
    path('offers/edit/<item_id>/', edit_offer, name='offer_edit'),
    path('offers/clear/<item_id>/', clear_offer, name='offer_clear'),
    path('offers/accept/<item_id>/', accept_offer, name='offer_accept'),
    path('offers/reject/<item_id>/', reject_offer, name='offer_reject'),
    path('offers/inactive/<item_id>/', inactive_offer, name='offer_inactive'),
    path('offers/delete/<item_id>/', delete_offer, name='offer_delete'),
    path('offers/export/', export_offer, name='offer_export'),
    path('offers/api/', OfferAPIJson.as_view(), name='offer_api'),

    path('camp/', camp, name='offer_camp'),
    path('check/', check, name='offer_check'),
    path('postback/', postback, name='offer_postback'),

    path('networks/', list_network, name='network_list'),
    path('networks/data_table/', login_required(NetworkListJson.as_view()), name='network_data_table'),
    path('networks/edit/<item_id>/', edit_network, name='network_edit'),
    path('networks/cron/<item_id>/', cron_network, name='network_cron'),
    path('networks/ajax_cron/<item_id>/<routing>/', ajax_cron, name='network_ajax_cron'),
    path('networks/api/', NetworkAPIJson.as_view(), name='network_api'),


    path('leads/', list_lead, name='lead_list'),
    path('leads/data_table/', login_required(LeadListJson.as_view()), name='lead_data_table'),
    path('leads/recent_lead/', recent_lead, name='recent_lead'),
    path('leads/notify_lead/', notify_lead, name='notify_lead'),
    path('leads/export/', export_lead, name='lead_export'),
    path('api/offers/', api_offer, name='api_offer'),
    path('api/users/', api_user, name='api_user'),

]

cpamaster/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('core/', include('core.urls')),
]

core/forms.py
from django import forms
from django.forms import ValidationError, ModelForm
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from core.models import *


class UserCacheMixin:
    user_cache = None


class SignIn(UserCacheMixin, forms.Form):
    password = forms.CharField(label=_('Password'), strip=False, widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if settings.USE_REMEMBER_ME:
            self.fields['remember_me'] = forms.BooleanField(label=_('Remember me'), required=False)

    def clean_password(self):
        password = self.cleaned_data['password']

        if not self.user_cache:
            return password

        if not self.user_cache.check_password(password):
            raise ValidationError(_('You entered an invalid password.'))

        return password


class SignInViaUsernameForm(SignIn):
    username = forms.CharField(label=_('Username'))

    @property
    def field_order(self):
        if settings.USE_REMEMBER_ME:
            return ['username', 'password', 'remember_me']
        return ['username', 'password']

    def clean_username(self):
        username = self.cleaned_data['username']

        user = User.objects.filter(username=username).first()
        if not user:
            raise ValidationError(_('You entered an invalid username.'))

        if not user.is_active:
            raise ValidationError(_('This account is not active.'))

        self.user_cache = user

        return username


class OfferForm(ModelForm):
    class Meta:
        model = Offer
        fields = '__all__'


class NetworkForm(ModelForm):
    class Meta:
        model = Network
        fields = ('name', 'cron_url', 'rate_offer', 'virtual_click', 'virtual_lead', 'active')

core/views.py
import logging
import subprocess

import xlwt
import calendar
import re
from django.contrib.auth import logout
from django.db.models import Sum
from django.http import JsonResponse, HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils import timezone
from django_countries import countries
from django.utils.safestring import mark_safe
from django.utils.timezone import now
from core.forms import *
from core.helpers import *
from datetime import datetime, timedelta, time
_logger = logging.getLogger('default')


def get_month_day_range(date):
    """
    For a date 'date' returns the start and end date for the month of 'date'.

    Month with 31 days:
    >>> date = datetime.date(2011, 7, 27)
    >>> get_month_day_range(date)
    (datetime.date(2011, 7, 1), datetime.date(2011, 7, 31))

    Month with 28 days:
    >>> date = datetime.date(2011, 2, 15)
    >>> get_month_day_range(date)
    (datetime.date(2011, 2, 1), datetime.date(2011, 2, 28))
    """
    first_day = date.replace(day=1)
    last_day = date.replace(day=calendar.monthrange(date.year, date.month)[1])
    return first_day, last_day


def log_out(request):
    logout(request)
    return redirect(reverse_lazy('core:login'))


def get_money(money):
    return round(money.get('offer_click_rate__sum'), 2) if money.get('offer_click_rate__sum') is not None else 0


def index(request):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))

    today_date = timezone.now().date()
    yesterday_date = today_date - timedelta(days=1)
    some_day_last_week = today_date - timedelta(days=7)
    monday_of_last_week = some_day_last_week - timedelta(days=(some_day_last_week.isocalendar()[2] - 1))
    start_of_this_week = monday_of_last_week + timedelta(days=7)
    end_of_this_week = start_of_this_week + timedelta(days=7)
    start_of_month, end_of_month = get_month_day_range(today_date)

    leads = Statistic.objects

    if not request.user.is_superuser:
        networks = Network.objects.filter(user=request.user)
        leads = leads.filter(offer_network_id__in=[x.id for x in networks])

    total_money = leads.aggregate(Sum('offer_click_rate'))
    today_money = leads.filter(created_at__date=today_date).aggregate(Sum('offer_click_rate'))

    month_money = leads.filter(Q(created_at__gte=start_of_month) & Q(created_at__lte=end_of_month)).aggregate(Sum('offer_click_rate'))

    today_leads = leads.filter(created_at__date=today_date)
    yesterday_leads = leads.filter(Q(created_at__gte=yesterday_date) & Q(created_at__lte=today_date))
    week_leads = leads.filter(Q(created_at__gte=start_of_this_week) & Q(created_at__lte=end_of_this_week))
    month_leads = leads.filter(Q(created_at__gte=start_of_month) & Q(created_at__lte=start_of_month))

    today_statistic_by_users = today_leads.values('click_user_name') \
        .annotate(sum_money=Sum('offer_click_rate')) \
        .order_by('-sum_money')

    today_statistic_by_networks = today_leads.values('offer_network_name') \
        .annotate(sum_money=Sum('offer_click_rate')) \
        .order_by('-sum_money')

    today_offers = {}
    week_offers = {}
    yesterday_offers = {}

    for lead in yesterday_leads:
        if lead.offer_id not in yesterday_offers:
            yesterday_offers[lead.offer_id] = {
                "name": "",
                "total_leads": 0,
                "total_money": 0,
                "price": 0,
            }
        yesterday_offers[lead.offer_id]["name"] = lead.offer_name
        yesterday_offers[lead.offer_id]["price"] = lead.offer_click_rate
        yesterday_offers[lead.offer_id]["total_leads"] += 1
        yesterday_offers[lead.offer_id]["total_money"] += lead.offer_click_rate

    for k, v in yesterday_offers.items():
        yesterday_offers[k]["total_clicks"] = Click.objects.filter(offer__id=k).filter(Q(created_at__gte=yesterday_date) & Q(created_at__lte=today_date)).count()
        if yesterday_offers[k]["total_clicks"] > 0:
            yesterday_offers[k]["site_cr"] = str(round((yesterday_offers[k]["total_leads"] / yesterday_offers[k]["total_clicks"]) * 100, 2)) + '%'
        else:
            yesterday_offers[k]["site_cr"] = "Not Available"

        yesterday_offers[k]["total_money"] = round(yesterday_offers[k]["total_money"], 2)

    for lead in week_leads:
        if lead.offer_id not in week_offers:
            week_offers[lead.offer_id] = {
                "name": "",
                "total_leads": 0,
                "total_money": 0,
                "price": 0,
            }
        week_offers[lead.offer_id]["name"] = lead.offer_name
        week_offers[lead.offer_id]["price"] = lead.offer_click_rate
        week_offers[lead.offer_id]["total_leads"] += 1
        week_offers[lead.offer_id]["total_money"] += lead.offer_click_rate

    for k, v in week_offers.items():
        week_offers[k]["total_clicks"] = Click.objects.filter(offer__id=k).filter(
            Q(created_at__gte=start_of_this_week) & Q(created_at__lte=end_of_this_week)).count()
        if week_offers[k]["total_clicks"] > 0:
            week_offers[k]["site_cr"] = str(
                round((week_offers[k]["total_leads"] / week_offers[k]["total_clicks"]) * 100, 2)) + '%'
        else:
            week_offers[k]["site_cr"] = "Not Available"

        week_offers[k]["total_money"] = round(week_offers[k]["total_money"], 2)

    for lead in today_leads:
        if lead.offer_id not in today_offers:
            today_offers[lead.offer_id] = {
                "name": "",
                "total_leads": 0,
                "total_money": 0,
                "price": 0,
            }
        today_offers[lead.offer_id]["name"] = lead.offer_name
        today_offers[lead.offer_id]["price"] = lead.offer_click_rate

        today_offers[lead.offer_id]["total_leads"] += 1
        today_offers[lead.offer_id]["total_money"] += lead.offer_click_rate

    for k, v in today_offers.items():
        today_offers[k]["total_clicks"] = Click.objects.filter(offer__id=k).filter(created_at__date=today_date).count()
        if today_offers[k]["total_clicks"] > 0:
            today_offers[k]["site_cr"] = str(
                round((today_offers[k]["total_leads"] / today_offers[k]["total_clicks"]) * 100, 2)) + '%'
        else:
            today_offers[k]["site_cr"] = "Not Available"

        today_offers[k]["total_money"] = round(today_offers[k]["total_money"], 2)

    return render(request, 'core/index.html', {
        'total_money': get_money(total_money),
        'today_money': get_money(today_money),
        'month_money': get_money(month_money),
        'today_leads': today_leads,
        'week_leads': week_leads,
        'month_leads': month_leads,
        'today_statistic_by_users': today_statistic_by_users,
        'today_offers': today_offers,
        'week_offers': week_offers,
        'yesterday_offers': yesterday_offers,
        'today_statistic_by_networks': today_statistic_by_networks,
    })


def list_offer(request):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))
    return render(request, 'core/offers/index.html')


def list_network(request):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))
    return render(request, 'core/networks/index.html')


def list_lead(request):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))
    return render(request, 'core/leads/index.html')


def recent_lead(request):

    if not request.user.is_superuser:
        networks = Network.objects.filter(user=request.user)
        recent_leads = Statistic.objects.filter(offer_network_id__in=[x.id for x in networks]).order_by('-updated_at')[:10]

    else:
        recent_leads = Statistic.objects.order_by('-updated_at')[:10]

    html = render_to_string('core/recent.html', {'recent_leads': recent_leads})

    return JsonResponse({'html': html})


def notify_lead(request):

    not_notify = 0

    if request.user:
        not_notify = Statistic.objects.filter(click_user_id=request.user.id).filter(is_sound_play=False).count()
        if not_notify > 0:
            Statistic.objects.filter(click_user_id=request.user.id).filter(is_sound_play=False).update(is_sound_play=True)

    return JsonResponse({'count': not_notify})

def create_offer(request):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))
    if request.method == 'POST':
        form = OfferForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('core:offer_list'))
    else:
        form = OfferForm()
    return render(request, 'core/offers/edit.html', {'form': form})


def edit_offer(request, item_id):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))
    offer = Offer.objects.get(pk=item_id)

    if request.method == 'POST':
        form = OfferForm(request.POST, instance=offer)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('core:offer_list'))
    else:
        form = OfferForm(instance=offer)
    return render(request, 'core/offers/edit.html', {'form': form})


def edit_network(request, item_id):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))
    content = Network.objects.get(pk=item_id)

    if request.method == 'POST':
        form = NetworkForm(request.POST, instance=content)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('core:network_list'))
    else:
        form = NetworkForm(instance=content)
    return render(request, 'core/networks/edit.html', {'form': form})


def clear_offer(request, item_id):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))

core/templates/core/networks/edit.html
{% extends 'core/base.html' %}
{% load static i18n core_helper countries %}

{% block styles %}
    <!-- Plugins css-->
    <link href="{% static "core/ubold/assets/plugins/bootstrap-tagsinput/css/bootstrap-tagsinput.css" %}" rel="stylesheet" />
    <link href="{% static "core/ubold/assets/plugins/switchery/css/switchery.min.css" %}" rel="stylesheet" />
    <link href="{% static "core/ubold/assets/plugins/multiselect/css/multi-select.css" %}"  rel="stylesheet" type="text/css" />
    <link href="{% static "core/ubold/assets/plugins/select2/css/select2.min.css" %}" rel="stylesheet" type="text/css" />
    <link href="{% static "core/ubold/assets/plugins/bootstrap-select/css/bootstrap-select.min.css" %}" rel="stylesheet" />
    <link href="{% static "core/ubold/assets/plugins/bootstrap-touchspin/css/jquery.bootstrap-touchspin.min.css" %}" rel="stylesheet" />
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="btn-group pull-right m-t-15">
                <a href="{% url 'core:network_list' %}" class="btn btn-primary waves-effect waves-light"><span class="m-r-5"><i class="fa fa-list"></i></span> List</a>
            </div>
            <h4 class="page-title">Chi tiết Network</h4>

        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card-box">
                <div class="row">
                    <div class="col-sm-12">
                        <form method="post" class="form-horizontal" id="edit_form" novalidate>
                            {% csrf_token %}
                            {% include 'core/common/form.html' with form=form %}
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right"></label>
                                <div class="col-sm-9">
                                    <button type="submit" class="btn btn-success waves-effect waves-light">Lưu</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static "core/ubold/assets/plugins/bootstrap-tagsinput/js/bootstrap-tagsinput.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/switchery/js/switchery.min.js" %}"></script>
    <script type="text/javascript" src="{% static "core/ubold/assets/plugins/multiselect/js/jquery.multi-select.js" %}"></script>
    <script type="text/javascript" src="{% static "core/ubold/assets/plugins/jquery-quicksearch/jquery.quicksearch.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/select2/js/select2.min.js" %}" type="text/javascript"></script>
    <script src="{% static "core/ubold/assets/plugins/bootstrap-select/js/bootstrap-select.min.js" %}" type="text/javascript"></script>
    <script src="{% static "core/ubold/assets/plugins/bootstrap-touchspin/js/jquery.bootstrap-touchspin.min.js" %}" type="text/javascript"></script>
    <script src="{% static "core/ubold/assets/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js" %}" type="text/javascript"></script>

    <script type="text/javascript" src="{% static "core/ubold/assets/plugins/autocomplete/jquery.mockjax.js" %}"></script>
    <script type="text/javascript" src="{% static "core/ubold/assets/plugins/autocomplete/jquery.autocomplete.min.js" %}"></script>
    <script type="text/javascript" src="{% static "core/ubold/assets/plugins/autocomplete/countries.js" %}"></script>
    <script type="text/javascript" src="{% static "core/ubold/assets/pages/autocomplete.js" %}"></script>

{% endblock %}
{% block inline_scripts %}



    <script>

        // Default

        var elems = Array.prototype.slice.call(document.querySelectorAll('#edit_form input[type="checkbox"]'));

        // if-else statement used only for fixing <IE9 issues
        if (Array.prototype.forEach) {

            elems.forEach(function(html) {
                var switchery = new Switchery(html);
            });
        } else {

            for (var i = 0; i < elems.length; i++) {
                var switchery = new Switchery(elems[i]);
            }
        }

        (function($){
            $('#edit_form select').select2();

        })(jQuery);
    </script>

{% endblock %}

core/templates/core/networks/index.html
{% extends 'core/base.html' %}
{% load static i18n core_helper countries %}
{% block inline_styles %}
    <style>
        .select2-container--default {
            width: 250px !important;
        }
        .select2-container--default .select2-results > .select2-results__options {
            max-height: 500px;
            min-height: 400px;
            overflow-y: auto;
        }
    </style>

{% endblock %}

{% block styles %}
    <!-- DataTables -->
    <link href="{% static "core/ubold/assets/plugins/datatables/jquery.dataTables.min.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "core/ubold/assets/plugins/datatables/buttons.bootstrap.min.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "core/ubold/assets/plugins/datatables/fixedHeader.bootstrap.min.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "core/ubold/assets/plugins/datatables/responsive.bootstrap.min.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "core/ubold/assets/plugins/datatables/scroller.bootstrap.min.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "core/ubold/assets/plugins/datatables/dataTables.colVis.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "core/ubold/assets/plugins/datatables/dataTables.bootstrap.min.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "core/ubold/assets/plugins/datatables/fixedColumns.dataTables.min.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "core/ubold/assets/plugins/select2/css/select2.min.css" %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <h4 class="page-title">Danh sách Network</h4>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card-box">
                <div class="row">
                    <div class="col-sm-12">
                        <form class="form-inline" role="form" id="search-form">
                            {% csrf_token %}

                            <div class="form-group m-l-10">
                                <label class="sr-only" for="">Network Name</label>
                                <input type="text" class="form-control" placeholder="Tên Network" name="name"/>
                            </div>



                            <div class="form-group m-l-10">
                                <label class="sr-only" for="">Active</label>
                                <select name="active" class="form-control select2">
                                    <option value="1">Active</option>
                                    <option value="0">Inactive</option>
                                </select>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="card-box table-responsive">
                <p class="text-muted font-13 m-b-30"></p>
                    <table id="dataTables" class="table table-striped table-bordered table-actions-bar">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Cron URL</th>
                                <th>Offer Count</th>
                                <th>Status</th>
                                <th>Update At</th>
                                <th>Last Cron At</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                    </table>

            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script src="{% static "core/ubold/assets/plugins/datatables/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/dataTables.bootstrap.js" %}"></script>

    <script src="{% static "core/ubold/assets/plugins/datatables/dataTables.buttons.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/buttons.bootstrap.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/jszip.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/pdfmake.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/vfs_fonts.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/buttons.html5.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/buttons.print.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/dataTables.fixedHeader.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/dataTables.keyTable.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/dataTables.responsive.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/responsive.bootstrap.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/dataTables.scroller.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/dataTables.colVis.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/dataTables.fixedColumns.min.js" %}"></script>

    <script src="{% static "core/ubold/assets/pages/datatables.init.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/select2/js/select2.full.min.js" %}"></script>
    <script src="{% static "core/js/handlebars.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/moment/moment.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/bootstrap-daterangepicker/daterangepicker.js" %}"></script>
{% endblock %}

{% block inline_scripts %}
    <script type="text/javascript">
        $('.select2').select2();

        $(function () {
            let dataTable = $("#dataTables").DataTable({
                searching: false,
                serverSide: true,
                processing: true,
                ajax: {
                    url: '{% url 'core:network_data_table' %}',
                    data: function (d) {
                        d.name = $('input[name=name]').val();
                        d.active = $('select[name=active]').val();
                    }
                },
                columns: [
                    {data: 'name', name: 'name', orderable: true},
                    {data: 'cron_url', name: 'cron_url', orderable: true},
                    {data: 'count_offer', name: 'count_offer', orderable: false},
                    {data: 'active', name: 'active', orderable: false},
                    {data: 'updated_at', name: 'updated_at', orderable: false},
                    {data: 'last_cron_at', name: 'last_cron_at', orderable: false},
                    {data: 'action', name: 'action', orderable: false},
                ],
                order: [[1, 'desc']]
            });

            $('#search-form input,select').on('change', function(e) {
                e.preventDefault();
                dataTable.draw();
            });
        });
    </script>
{% endblock %}