core/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from core.classes import *
from core.views import *

app_name = 'core'

urlpatterns = [
    path('login/', LogInView.as_view(), name='login'),
    path('logout/', log_out, name='logout'),
    path('offers/', list_offer, name='offer_list'),

    path('offers/create/', create_offer, name='offer_create'),
    path('offers/data_table/', login_required(OfferListJson.as_view()), name='offer_data_table'),
    path('offers/edit/<item_id>/', edit_offer, name='offer_edit'),
    path('offers/clear/<item_id>/', clear_offer, name='offer_clear'),
    path('offers/accept/<item_id>/', accept_offer, name='offer_accept'),
    path('offers/reject/<item_id>/', reject_offer, name='offer_reject'),
    path('offers/inactive/<item_id>/', inactive_offer, name='offer_inactive'),
    path('offers/delete/<item_id>/', delete_offer, name='offer_delete'),
    path('offers/export/', export_offer, name='offer_export'),
    path('offers/api/', OfferAPIJson.as_view(), name='offer_api'),

    path('camp/', camp, name='offer_camp'),
    path('check/', check, name='offer_check'),
    path('postback/', postback, name='offer_postback'),

    path('networks/', list_network, name='network_list'),
    path('networks/data_table/', login_required(NetworkListJson.as_view()), name='network_data_table'),
    path('networks/edit/<item_id>/', edit_network, name='network_edit'),
    path('networks/cron/<item_id>/', cron_network, name='network_cron'),
    path('networks/ajax_cron/<item_id>/<routing>/', ajax_cron, name='network_ajax_cron'),
    path('networks/api/', NetworkAPIJson.as_view(), name='network_api'),


    path('leads/', list_lead, name='lead_list'),
    path('leads/data_table/', login_required(LeadListJson.as_view()), name='lead_data_table'),
    path('leads/recent_lead/', recent_lead, name='recent_lead'),
    path('leads/notify_lead/', notify_lead, name='notify_lead'),
    path('leads/export/', export_lead, name='lead_export'),
    path('api/offers/', api_offer, name='api_offer'),
    path('api/users/', api_user, name='api_user'),

]

cpamaster/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('core/', include('core.urls')),
]

core/forms.py
from django import forms
from django.forms import ValidationError, ModelForm
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from core.models import *


class UserCacheMixin:
    user_cache = None


class SignIn(UserCacheMixin, forms.Form):
    password = forms.CharField(label=_('Password'), strip=False, widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if settings.USE_REMEMBER_ME:
            self.fields['remember_me'] = forms.BooleanField(label=_('Remember me'), required=False)

    def clean_password(self):
        password = self.cleaned_data['password']

        if not self.user_cache:
            return password

        if not self.user_cache.check_password(password):
            raise ValidationError(_('You entered an invalid password.'))

        return password


class SignInViaUsernameForm(SignIn):
    username = forms.CharField(label=_('Username'))

    @property
    def field_order(self):
        if settings.USE_REMEMBER_ME:
            return ['username', 'password', 'remember_me']
        return ['username', 'password']

    def clean_username(self):
        username = self.cleaned_data['username']

        user = User.objects.filter(username=username).first()
        if not user:
            raise ValidationError(_('You entered an invalid username.'))

        if not user.is_active:
            raise ValidationError(_('This account is not active.'))

        self.user_cache = user

        return username


class OfferForm(ModelForm):
    class Meta:
        model = Offer
        fields = '__all__'


class NetworkForm(ModelForm):
    class Meta:
        model = Network
        fields = ('name', 'cron_url', 'rate_offer', 'virtual_click', 'virtual_lead', 'active')

core/views.py
import logging
import subprocess

import xlwt
import calendar
import re
from django.contrib.auth import logout
from django.db.models import Sum
from django.http import JsonResponse, HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils import timezone
from django_countries import countries
from django.utils.safestring import mark_safe
from django.utils.timezone import now
from core.forms import *
from core.helpers import *
from datetime import datetime, timedelta, time
_logger = logging.getLogger('default')


def get_month_day_range(date):
    """
    For a date 'date' returns the start and end date for the month of 'date'.

    Month with 31 days:
    >>> date = datetime.date(2011, 7, 27)
    >>> get_month_day_range(date)
    (datetime.date(2011, 7, 1), datetime.date(2011, 7, 31))

    Month with 28 days:
    >>> date = datetime.date(2011, 2, 15)
    >>> get_month_day_range(date)
    (datetime.date(2011, 2, 1), datetime.date(2011, 2, 28))
    """
    first_day = date.replace(day=1)
    last_day = date.replace(day=calendar.monthrange(date.year, date.month)[1])
    return first_day, last_day


def log_out(request):
    logout(request)
    return redirect(reverse_lazy('core:login'))


def get_money(money):
    return round(money.get('offer_click_rate__sum'), 2) if money.get('offer_click_rate__sum') is not None else 0


def index(request):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))

    today_date = timezone.now().date()
    yesterday_date = today_date - timedelta(days=1)
    some_day_last_week = today_date - timedelta(days=7)
    monday_of_last_week = some_day_last_week - timedelta(days=(some_day_last_week.isocalendar()[2] - 1))
    start_of_this_week = monday_of_last_week + timedelta(days=7)
    end_of_this_week = start_of_this_week + timedelta(days=7)
    start_of_month, end_of_month = get_month_day_range(today_date)

    leads = Statistic.objects

    if not request.user.is_superuser:
        networks = Network.objects.filter(user=request.user)
        leads = leads.filter(offer_network_id__in=[x.id for x in networks])

    total_money = leads.aggregate(Sum('offer_click_rate'))
    today_money = leads.filter(created_at__date=today_date).aggregate(Sum('offer_click_rate'))

    month_money = leads.filter(Q(created_at__gte=start_of_month) & Q(created_at__lte=end_of_month)).aggregate(Sum('offer_click_rate'))

    today_leads = leads.filter(created_at__date=today_date)
    yesterday_leads = leads.filter(Q(created_at__gte=yesterday_date) & Q(created_at__lte=today_date))
    week_leads = leads.filter(Q(created_at__gte=start_of_this_week) & Q(created_at__lte=end_of_this_week))
    month_leads = leads.filter(Q(created_at__gte=start_of_month) & Q(created_at__lte=start_of_month))

    today_statistic_by_users = today_leads.values('click_user_name') \
        .annotate(sum_money=Sum('offer_click_rate')) \
        .order_by('-sum_money')

    today_statistic_by_networks = today_leads.values('offer_network_name') \
        .annotate(sum_money=Sum('offer_click_rate')) \
        .order_by('-sum_money')

    today_offers = {}
    week_offers = {}
    yesterday_offers = {}

    for lead in yesterday_leads:
        if lead.offer_id not in yesterday_offers:
            yesterday_offers[lead.offer_id] = {
                "name": "",
                "total_leads": 0,
                "total_money": 0,
                "price": 0,
            }
        yesterday_offers[lead.offer_id]["name"] = lead.offer_name
        yesterday_offers[lead.offer_id]["price"] = lead.offer_click_rate
        yesterday_offers[lead.offer_id]["total_leads"] += 1
        yesterday_offers[lead.offer_id]["total_money"] += lead.offer_click_rate

    for k, v in yesterday_offers.items():
        yesterday_offers[k]["total_clicks"] = Click.objects.filter(offer__id=k).filter(Q(created_at__gte=yesterday_date) & Q(created_at__lte=today_date)).count()
        if yesterday_offers[k]["total_clicks"] > 0:
            yesterday_offers[k]["site_cr"] = str(round((yesterday_offers[k]["total_leads"] / yesterday_offers[k]["total_clicks"]) * 100, 2)) + '%'
        else:
            yesterday_offers[k]["site_cr"] = "Not Available"

        yesterday_offers[k]["total_money"] = round(yesterday_offers[k]["total_money"], 2)

    for lead in week_leads:
        if lead.offer_id not in week_offers:
            week_offers[lead.offer_id] = {
                "name": "",
                "total_leads": 0,
                "total_money": 0,
                "price": 0,
            }
        week_offers[lead.offer_id]["name"] = lead.offer_name
        week_offers[lead.offer_id]["price"] = lead.offer_click_rate
        week_offers[lead.offer_id]["total_leads"] += 1
        week_offers[lead.offer_id]["total_money"] += lead.offer_click_rate

    for k, v in week_offers.items():
        week_offers[k]["total_clicks"] = Click.objects.filter(offer__id=k).filter(
            Q(created_at__gte=start_of_this_week) & Q(created_at__lte=end_of_this_week)).count()
        if week_offers[k]["total_clicks"] > 0:
            week_offers[k]["site_cr"] = str(
                round((week_offers[k]["total_leads"] / week_offers[k]["total_clicks"]) * 100, 2)) + '%'
        else:
            week_offers[k]["site_cr"] = "Not Available"

        week_offers[k]["total_money"] = round(week_offers[k]["total_money"], 2)

    for lead in today_leads:
        if lead.offer_id not in today_offers:
            today_offers[lead.offer_id] = {
                "name": "",
                "total_leads": 0,
                "total_money": 0,
                "price": 0,
            }
        today_offers[lead.offer_id]["name"] = lead.offer_name
        today_offers[lead.offer_id]["price"] = lead.offer_click_rate

        today_offers[lead.offer_id]["total_leads"] += 1
        today_offers[lead.offer_id]["total_money"] += lead.offer_click_rate

    for k, v in today_offers.items():
        today_offers[k]["total_clicks"] = Click.objects.filter(offer__id=k).filter(created_at__date=today_date).count()
        if today_offers[k]["total_clicks"] > 0:
            today_offers[k]["site_cr"] = str(
                round((today_offers[k]["total_leads"] / today_offers[k]["total_clicks"]) * 100, 2)) + '%'
        else:
            today_offers[k]["site_cr"] = "Not Available"

        today_offers[k]["total_money"] = round(today_offers[k]["total_money"], 2)

    return render(request, 'core/index.html', {
        'total_money': get_money(total_money),
        'today_money': get_money(today_money),
        'month_money': get_money(month_money),
        'today_leads': today_leads,
        'week_leads': week_leads,
        'month_leads': month_leads,
        'today_statistic_by_users': today_statistic_by_users,
        'today_offers': today_offers,
        'week_offers': week_offers,
        'yesterday_offers': yesterday_offers,
        'today_statistic_by_networks': today_statistic_by_networks,
    })


def list_offer(request):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))
    return render(request, 'core/offers/index.html')


def list_network(request):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))
    return render(request, 'core/networks/index.html')


def list_lead(request):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))
    return render(request, 'core/leads/index.html')


def recent_lead(request):

    if not request.user.is_superuser:
        networks = Network.objects.filter(user=request.user)
        recent_leads = Statistic.objects.filter(offer_network_id__in=[x.id for x in networks]).order_by('-updated_at')[:10]

    else:
        recent_leads = Statistic.objects.order_by('-updated_at')[:10]

    html = render_to_string('core/recent.html', {'recent_leads': recent_leads})

    return JsonResponse({'html': html})


def notify_lead(request):

    not_notify = 0

    if request.user:
        not_notify = Statistic.objects.filter(click_user_id=request.user.id).filter(is_sound_play=False).count()
        if not_notify > 0:
            Statistic.objects.filter(click_user_id=request.user.id).filter(is_sound_play=False).update(is_sound_play=True)

    return JsonResponse({'count': not_notify})

def create_offer(request):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))
    if request.method == 'POST':
        form = OfferForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('core:offer_list'))
    else:
        form = OfferForm()
    return render(request, 'core/offers/edit.html', {'form': form})


def edit_offer(request, item_id):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))
    offer = Offer.objects.get(pk=item_id)

    if request.method == 'POST':
        form = OfferForm(request.POST, instance=offer)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('core:offer_list'))
    else:
        form = OfferForm(instance=offer)
    return render(request, 'core/offers/edit.html', {'form': form})


def edit_network(request, item_id):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))
    content = Network.objects.get(pk=item_id)

    if request.method == 'POST':
        form = NetworkForm(request.POST, instance=content)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('core:network_list'))
    else:
        form = NetworkForm(instance=content)
    return render(request, 'core/networks/edit.html', {'form': form})


def clear_offer(request, item_id):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))

core/templates/core/common/data_range_picker.html
<script>
    $(function () {
        $('.input-daterange-datepicker').daterangepicker({
            autoUpdateInput: false,
            dateLimit: {
                days: 60
            },
            showDropdowns: true,
            showWeekNumbers: true,
            timePicker: false,
            timePickerIncrement: 1,
            timePicker12Hour: true,
            ranges: {
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            },
            opens: 'left',
            drops: 'down',
            buttonClasses: ['btn', 'btn-sm'],
            applyClass: 'btn-default',
            cancelClass: 'btn-white',
            separator: ' to ',
            locale: {
                format: 'DD/MM/YYYY',
                applyLabel: 'Submit',
                cancelLabel: 'Clear',
                fromLabel: 'From',
                toLabel: 'To',
                customRangeLabel: 'Custom',
                daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
                monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                firstDay: 1
            }
        });

        $('.input-daterange-datepicker').on('apply.daterangepicker', function(ev, picker) {
            $(this).val(picker.startDate.format('DD/MM/YYYY') + ' - ' + picker.endDate.format('DD/MM/YYYY'));
        });

        $('.input-daterange-datepicker').on('cancel.daterangepicker', function(ev, picker) {
        });
    });
</script>

core/templates/core/common/footer.html
<footer class="footer text-right">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                © 2018. All rights reserved.
            </div>
        </div>
    </div>
</footer>

core/templates/core/common/form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
            {{ error }}
        {% endfor %}
    </div>
{% endif %}

{% for field in form.visible_fields %}
    <div class="form-group">
        <label class="col-md-3 control-label">{{ field.label }}</label>
        <div class="col-md-9">
        {% if form.is_bound %}
            {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        {{ error }}
                    </div>
                {% endfor %}
            {% else %}
                {% render_field field class="form-control is-valid" %}
            {% endif %}
        {% else %}
            {% render_field field class="form-control" %}
        {% endif %}

        {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
        </div>
    </div>
{% endfor %}

core/templates/core/common/header.html
{% load static i18n core_helper %}
<header id="topnav">
    <div class="topbar-main">
        <div class="container">

            <!-- Logo container-->
            <div class="logo">
                <a href="{% url 'index' %}" class="logo"><span>{% settings_value "APP_NAME" %}</span></a>
            </div>
            <!-- End Logo container-->


            <div class="menu-extras">

                <ul class="nav navbar-nav navbar-right pull-right">
                    <li class="hidden-xs">
                        <a href="#" id="btn-fullscreen" class="waves-effect waves-light"><i class="icon-size-fullscreen"></i></a>
                    </li>

                    <li class="dropdown navbar-c-items">
                        <a href="" class="dropdown-toggle waves-effect waves-light profile" data-toggle="dropdown"
                           aria-expanded="true"><img src="{% static "core/ubold/assets/images/user.png" %}" alt="user-img"
                                                     class="img-circle"> </a>
                    </li>
                    <li><a href="{% url 'core:logout' %}"><i class="ti-power-off text-danger m-r-10"></i> Logout</a>
                </ul>
                <div class="menu-item">
                    <!-- Mobile menu toggle-->
                    <a class="navbar-toggle">
                        <div class="lines">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </a>
                    <!-- End mobile menu toggle-->
                </div>
            </div>

        </div>
    </div>

    {% include 'core/common/navbar.html' %}
</header>

core/templates/core/common/navbar.html
{% load static i18n core_helper %}
<div class="navbar-custom">
    <div class="container">
        <div id="navigation">
            <!-- Navigation Menu-->
            <ul class="navigation-menu">
                <li class="has-submenu">
                    <a href="{% url 'index' %}"><i class="md md-dashboard"></i>Trang chủ</a>
                </li>

                <li class="has-submenu">
                    <a href="{% url 'core:offer_list' %}"><i class="md md-dashboard"></i>Offers</a>
                </li>
                <li class="has-submenu"><a href="{% url 'core:lead_list' %}"><i class="md md-dashboard"></i>Statistics</a></li>

                 {% if request.user.is_staff %}
                 <li class="has-submenu"><a href="{% url 'core:network_list' %}"><i class="md md-dashboard"></i>Networks</a></li>

                 {% endif %}

                {% if request.user.is_superuser %}
                    <li class="has-submenu">
                        <a href="{% url 'admin:index' %}"><i class="md md-class"></i>Admin</a>
                    </li>
                {% endif %}

            </ul>
            <!-- End navigation menu        -->
        </div>
    </div> <!-- end container -->
</div> <!-- end navbar-custom -->