core/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from core.classes import *
from core.views import *

app_name = 'core'

urlpatterns = [
    path('login/', LogInView.as_view(), name='login'),
    path('logout/', log_out, name='logout'),
    path('offers/', list_offer, name='offer_list'),

    path('offers/create/', create_offer, name='offer_create'),
    path('offers/data_table/', login_required(OfferListJson.as_view()), name='offer_data_table'),
    path('offers/edit/<item_id>/', edit_offer, name='offer_edit'),
    path('offers/clear/<item_id>/', clear_offer, name='offer_clear'),
    path('offers/accept/<item_id>/', accept_offer, name='offer_accept'),
    path('offers/reject/<item_id>/', reject_offer, name='offer_reject'),
    path('offers/inactive/<item_id>/', inactive_offer, name='offer_inactive'),
    path('offers/delete/<item_id>/', delete_offer, name='offer_delete'),
    path('offers/export/', export_offer, name='offer_export'),
    path('offers/api/', OfferAPIJson.as_view(), name='offer_api'),

    path('camp/', camp, name='offer_camp'),
    path('check/', check, name='offer_check'),
    path('postback/', postback, name='offer_postback'),

    path('networks/', list_network, name='network_list'),
    path('networks/data_table/', login_required(NetworkListJson.as_view()), name='network_data_table'),
    path('networks/edit/<item_id>/', edit_network, name='network_edit'),
    path('networks/cron/<item_id>/', cron_network, name='network_cron'),
    path('networks/ajax_cron/<item_id>/<routing>/', ajax_cron, name='network_ajax_cron'),
    path('networks/api/', NetworkAPIJson.as_view(), name='network_api'),


    path('leads/', list_lead, name='lead_list'),
    path('leads/data_table/', login_required(LeadListJson.as_view()), name='lead_data_table'),
    path('leads/recent_lead/', recent_lead, name='recent_lead'),
    path('leads/notify_lead/', notify_lead, name='notify_lead'),
    path('leads/export/', export_lead, name='lead_export'),
    path('api/offers/', api_offer, name='api_offer'),
    path('api/users/', api_user, name='api_user'),

]

cpamaster/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('core/', include('core.urls')),
]

core/forms.py
from django import forms
from django.forms import ValidationError, ModelForm
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from core.models import *


class UserCacheMixin:
    user_cache = None


class SignIn(UserCacheMixin, forms.Form):
    password = forms.CharField(label=_('Password'), strip=False, widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if settings.USE_REMEMBER_ME:
            self.fields['remember_me'] = forms.BooleanField(label=_('Remember me'), required=False)

    def clean_password(self):
        password = self.cleaned_data['password']

        if not self.user_cache:
            return password

        if not self.user_cache.check_password(password):
            raise ValidationError(_('You entered an invalid password.'))

        return password


class SignInViaUsernameForm(SignIn):
    username = forms.CharField(label=_('Username'))

    @property
    def field_order(self):
        if settings.USE_REMEMBER_ME:
            return ['username', 'password', 'remember_me']
        return ['username', 'password']

    def clean_username(self):
        username = self.cleaned_data['username']

        user = User.objects.filter(username=username).first()
        if not user:
            raise ValidationError(_('You entered an invalid username.'))

        if not user.is_active:
            raise ValidationError(_('This account is not active.'))

        self.user_cache = user

        return username


class OfferForm(ModelForm):
    class Meta:
        model = Offer
        fields = '__all__'


class NetworkForm(ModelForm):
    class Meta:
        model = Network
        fields = ('name', 'cron_url', 'rate_offer', 'virtual_click', 'virtual_lead', 'active')

core/views.py
import logging
import subprocess

import xlwt
import calendar
import re
from django.contrib.auth import logout
from django.db.models import Sum
from django.http import JsonResponse, HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils import timezone
from django_countries import countries
from django.utils.safestring import mark_safe
from django.utils.timezone import now
from core.forms import *
from core.helpers import *
from datetime import datetime, timedelta, time
_logger = logging.getLogger('default')


def get_month_day_range(date):
    """
    For a date 'date' returns the start and end date for the month of 'date'.

    Month with 31 days:
    >>> date = datetime.date(2011, 7, 27)
    >>> get_month_day_range(date)
    (datetime.date(2011, 7, 1), datetime.date(2011, 7, 31))

    Month with 28 days:
    >>> date = datetime.date(2011, 2, 15)
    >>> get_month_day_range(date)
    (datetime.date(2011, 2, 1), datetime.date(2011, 2, 28))
    """
    first_day = date.replace(day=1)
    last_day = date.replace(day=calendar.monthrange(date.year, date.month)[1])
    return first_day, last_day


def log_out(request):
    logout(request)
    return redirect(reverse_lazy('core:login'))


def get_money(money):
    return round(money.get('offer_click_rate__sum'), 2) if money.get('offer_click_rate__sum') is not None else 0


def index(request):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))

    today_date = timezone.now().date()
    yesterday_date = today_date - timedelta(days=1)
    some_day_last_week = today_date - timedelta(days=7)
    monday_of_last_week = some_day_last_week - timedelta(days=(some_day_last_week.isocalendar()[2] - 1))
    start_of_this_week = monday_of_last_week + timedelta(days=7)
    end_of_this_week = start_of_this_week + timedelta(days=7)
    start_of_month, end_of_month = get_month_day_range(today_date)

    leads = Statistic.objects

    if not request.user.is_superuser:
        networks = Network.objects.filter(user=request.user)
        leads = leads.filter(offer_network_id__in=[x.id for x in networks])

    total_money = leads.aggregate(Sum('offer_click_rate'))
    today_money = leads.filter(created_at__date=today_date).aggregate(Sum('offer_click_rate'))

    month_money = leads.filter(Q(created_at__gte=start_of_month) & Q(created_at__lte=end_of_month)).aggregate(Sum('offer_click_rate'))

    today_leads = leads.filter(created_at__date=today_date)
    yesterday_leads = leads.filter(Q(created_at__gte=yesterday_date) & Q(created_at__lte=today_date))
    week_leads = leads.filter(Q(created_at__gte=start_of_this_week) & Q(created_at__lte=end_of_this_week))
    month_leads = leads.filter(Q(created_at__gte=start_of_month) & Q(created_at__lte=start_of_month))

    today_statistic_by_users = today_leads.values('click_user_name') \
        .annotate(sum_money=Sum('offer_click_rate')) \
        .order_by('-sum_money')

    today_statistic_by_networks = today_leads.values('offer_network_name') \
        .annotate(sum_money=Sum('offer_click_rate')) \
        .order_by('-sum_money')

    today_offers = {}
    week_offers = {}
    yesterday_offers = {}

    for lead in yesterday_leads:
        if lead.offer_id not in yesterday_offers:
            yesterday_offers[lead.offer_id] = {
                "name": "",
                "total_leads": 0,
                "total_money": 0,
                "price": 0,
            }
        yesterday_offers[lead.offer_id]["name"] = lead.offer_name
        yesterday_offers[lead.offer_id]["price"] = lead.offer_click_rate
        yesterday_offers[lead.offer_id]["total_leads"] += 1
        yesterday_offers[lead.offer_id]["total_money"] += lead.offer_click_rate

    for k, v in yesterday_offers.items():
        yesterday_offers[k]["total_clicks"] = Click.objects.filter(offer__id=k).filter(Q(created_at__gte=yesterday_date) & Q(created_at__lte=today_date)).count()
        if yesterday_offers[k]["total_clicks"] > 0:
            yesterday_offers[k]["site_cr"] = str(round((yesterday_offers[k]["total_leads"] / yesterday_offers[k]["total_clicks"]) * 100, 2)) + '%'
        else:
            yesterday_offers[k]["site_cr"] = "Not Available"

        yesterday_offers[k]["total_money"] = round(yesterday_offers[k]["total_money"], 2)

    for lead in week_leads:
        if lead.offer_id not in week_offers:
            week_offers[lead.offer_id] = {
                "name": "",
                "total_leads": 0,
                "total_money": 0,
                "price": 0,
            }
        week_offers[lead.offer_id]["name"] = lead.offer_name
        week_offers[lead.offer_id]["price"] = lead.offer_click_rate
        week_offers[lead.offer_id]["total_leads"] += 1
        week_offers[lead.offer_id]["total_money"] += lead.offer_click_rate

    for k, v in week_offers.items():
        week_offers[k]["total_clicks"] = Click.objects.filter(offer__id=k).filter(
            Q(created_at__gte=start_of_this_week) & Q(created_at__lte=end_of_this_week)).count()
        if week_offers[k]["total_clicks"] > 0:
            week_offers[k]["site_cr"] = str(
                round((week_offers[k]["total_leads"] / week_offers[k]["total_clicks"]) * 100, 2)) + '%'
        else:
            week_offers[k]["site_cr"] = "Not Available"

        week_offers[k]["total_money"] = round(week_offers[k]["total_money"], 2)

    for lead in today_leads:
        if lead.offer_id not in today_offers:
            today_offers[lead.offer_id] = {
                "name": "",
                "total_leads": 0,
                "total_money": 0,
                "price": 0,
            }
        today_offers[lead.offer_id]["name"] = lead.offer_name
        today_offers[lead.offer_id]["price"] = lead.offer_click_rate

        today_offers[lead.offer_id]["total_leads"] += 1
        today_offers[lead.offer_id]["total_money"] += lead.offer_click_rate

    for k, v in today_offers.items():
        today_offers[k]["total_clicks"] = Click.objects.filter(offer__id=k).filter(created_at__date=today_date).count()
        if today_offers[k]["total_clicks"] > 0:
            today_offers[k]["site_cr"] = str(
                round((today_offers[k]["total_leads"] / today_offers[k]["total_clicks"]) * 100, 2)) + '%'
        else:
            today_offers[k]["site_cr"] = "Not Available"

        today_offers[k]["total_money"] = round(today_offers[k]["total_money"], 2)

    return render(request, 'core/index.html', {
        'total_money': get_money(total_money),
        'today_money': get_money(today_money),
        'month_money': get_money(month_money),
        'today_leads': today_leads,
        'week_leads': week_leads,
        'month_leads': month_leads,
        'today_statistic_by_users': today_statistic_by_users,
        'today_offers': today_offers,
        'week_offers': week_offers,
        'yesterday_offers': yesterday_offers,
        'today_statistic_by_networks': today_statistic_by_networks,
    })


def list_offer(request):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))
    return render(request, 'core/offers/index.html')


def list_network(request):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))
    return render(request, 'core/networks/index.html')


def list_lead(request):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))
    return render(request, 'core/leads/index.html')


def recent_lead(request):

    if not request.user.is_superuser:
        networks = Network.objects.filter(user=request.user)
        recent_leads = Statistic.objects.filter(offer_network_id__in=[x.id for x in networks]).order_by('-updated_at')[:10]

    else:
        recent_leads = Statistic.objects.order_by('-updated_at')[:10]

    html = render_to_string('core/recent.html', {'recent_leads': recent_leads})

    return JsonResponse({'html': html})


def notify_lead(request):

    not_notify = 0

    if request.user:
        not_notify = Statistic.objects.filter(click_user_id=request.user.id).filter(is_sound_play=False).count()
        if not_notify > 0:
            Statistic.objects.filter(click_user_id=request.user.id).filter(is_sound_play=False).update(is_sound_play=True)

    return JsonResponse({'count': not_notify})

def create_offer(request):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))
    if request.method == 'POST':
        form = OfferForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('core:offer_list'))
    else:
        form = OfferForm()
    return render(request, 'core/offers/edit.html', {'form': form})


def edit_offer(request, item_id):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))
    offer = Offer.objects.get(pk=item_id)

    if request.method == 'POST':
        form = OfferForm(request.POST, instance=offer)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('core:offer_list'))
    else:
        form = OfferForm(instance=offer)
    return render(request, 'core/offers/edit.html', {'form': form})


def edit_network(request, item_id):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))
    content = Network.objects.get(pk=item_id)

    if request.method == 'POST':
        form = NetworkForm(request.POST, instance=content)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('core:network_list'))
    else:
        form = NetworkForm(instance=content)
    return render(request, 'core/networks/edit.html', {'form': form})


def clear_offer(request, item_id):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))

core/templates/core/base.html
{% load static i18n core_helper %}<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="QuanDM">
    <!-- App Favicon icon -->
    <link rel="shortcut icon" href="">
    <!-- App Title -->
    <title>{% settings_value "APP_NAME" %}</title>
    <meta name="csrf_token" content="{{ csrf_token }}" />

    {% block styles %}{% endblock %}
    <link rel="stylesheet" href="{% static "core/css/app.css" %}">
    <link href="{% static "core/ubold/assets/css/bootstrap.min.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "core/ubold/assets/css/core.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "core/ubold/assets/css/components.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "core/ubold/assets/css/icons.css" %}" rel="stylesheet" type="text/css"/>

    {% block styles_pages %}{% endblock %}

    <link href="{% static "core/ubold/assets/css/pages.css" %}" rel="stylesheet" type="text/css"/>

    <link href="{% static "core/ubold/assets/css/menu.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "core/ubold/assets/css/responsive.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "core/css/admin/sweetalert2.min.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "core/backend/js/vis-4.20.1/dist/vis.css" %}" rel="stylesheet" type="text/css" />
    {% block inline_styles %}{% endblock %}

    <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script src="{% static "core/ubold/assets/js/modernizr.min.js" %}"></script>


</head>

<body>

{% if request.user.is_authenticated %}
<!-- Navigation Bar-->
{% include 'core/common/header.html' %}
<!-- End Navigation Bar-->
{% endif %}
<div class="wrapper">
    <div class="container">
        {% block content %}{% endblock %}
        <!-- Footer -->
        {% include 'core/common/footer.html' %}
        <!-- End Footer -->
    </div> <!-- end container -->
</div>

<!-- jQuery  -->
<script src="{% static "core/ubold/assets/js/jquery.min.js" %}"></script>
<script src="{% static "core/ubold/assets/js/bootstrap.min.js" %}"></script>
<script src="{% static "core/ubold/assets/js/detect.js" %}"></script>
<script src="{% static "core/ubold/assets/js/fastclick.js" %}"></script>
<script src="{% static "core/ubold/assets/js/jquery.slimscroll.js" %}"></script>
<script src="{% static "core/ubold/assets/js/jquery.blockUI.js" %}"></script>
<script src="{% static "core/ubold/assets/js/waves.js" %}"></script>
<script src="{% static "core/ubold/assets/js/wow.min.js" %}"></script>
<script src="{% static "core/ubold/assets/js/jquery.nicescroll.js" %}"></script>
<script src="{% static "core/ubold/assets/js/jquery.scrollTo.min.js" %}"></script>
<script src="{% static "core/js/admin/sweetalert2.min.js" %}"></script>
{% block scripts %}{% endblock %}

<!-- App core js -->
<script src="{% static "core/ubold/assets/js/jquery.core.js" %}"></script>
<script src="{% static "core/ubold/assets/js/jquery.app.js" %}"></script>

<script type="text/javascript">
    $.ajaxSetup({
        headers: { 'X-CSRF-Token' : $('meta[name=csrf_token]').attr('content') }
    });
</script>
{% block inline_scripts %}{% endblock %}
<script src="{% static "core/js/alert.js" %}"></script>
{% if request.user %}
    <script>
        $(document).ready(function(){
            setInterval(function(){
                //  $('#site-recent-lead').html('<img width="200" align="center" height="auto" src="/image/loading.gif" />');
                $.getJSON('{% url 'core:notify_lead' %}', function(response){
                    if (parseInt(response.count) > 0) {
                        playAlert('custom');
                    }
                });
            }, 10000);
        });
    </script>
{% endif %}
</body>
</html>

core/templates/core/login.html
{% extends 'core/base.html' %}
{% load i18n bootstrap4 core_helper %}

{% block content %}


    <div class="wrapper-page">
        <div class="card-box">
            <div class="panel-heading">
                <h3 class="text-center"> Sign In to <strong class="text-custom">{% settings_value "APP_NAME" %}</strong></h3>
            </div>

            <div class="panel-body">
                <form method="post">

                    {% csrf_token %}
                    {% bootstrap_form form %}

                    <button class="btn btn-primary">{% trans 'Log in' %}</button>

                </form>

            </div>
        </div>

    </div>

{% endblock %}

core/templates/core/rabbit.html
{% load static %}
<!DOCTYPE html>
<html><head>
  <script src="{% static 'core/rabbit/js/jquery.min.js' %}"></script>
  <script src="{% static 'core/rabbit/js/sockjs.min.js' %}"></script>

  <script src="{% static 'core/rabbit/js/stomp.js' %}"></script>
  <style>
      .box {
          width: 440px;
          float: left;
          margin: 0 20px 0 20px;
      }

      .box div, .box input {
          border: 1px solid;
          -moz-border-radius: 4px;
          border-radius: 4px;
          width: 100%;
          padding: 5px;
          margin: 3px 0 10px 0;
      }

      .box div {
          border-color: grey;
          height: 300px;
          overflow: auto;
      }

      div code {
          display: block;
      }

      #first div code {
          -moz-border-radius: 2px;
          border-radius: 2px;
          border: 1px solid #eee;
          margin-bottom: 5px;
      }

      #second div {
          font-size: 0.8em;
      }
  </style>
  <title>RabbitMQ Web STOMP Examples : Temporary Queue</title>

</head><body lang="en">

    <div id="first">
      <h2>Received</h2>
      <div></div>
    </div>

    {% if debug %}
        <div id="second" style="display: block">
            <h2>Logs</h2>
            <div></div>
        </div>
    {% else %}
        <div id="second" style="display: none">
            <h2>Logs</h2>
            <div></div>
        </div>
    {% endif %}



    <script>
      $(function(){
          $.get('{% url 'core:network_ajax_cron' network_id routing %}', function(response){
              console.log(response);
          })
      });

      if (location.search == '?ws') {
          var ws = new WebSocket('ws://{{ server_ip }}:15674/ws');
      } else {
          var ws = new SockJS('http://{{ server_ip }}:15674/stomp');
      }
      var client = Stomp.over(ws);

      client.heartbeat.outgoing=0;
      client.heartbeat.incoming=0;

      client.debug = function(e) {
          $('#second div').append($("<code>").text(e));
      };



      var on_connect = function(x) {
          id = client.subscribe("/queue/{{ routing }}", function(m) {
              $('#first div').append($("<code>").text(m.body));
          });
      };
      var on_error =  function() {
        console.log('error');
      };
      client.connect('admin', 'password', on_connect, on_error, '/');
    </script>
</body></html>

core/templates/core/recent.html
<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            <i class="fa fa-bell fa-fw"></i>Site Recent Lead
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
            <div class="list-group">
                {% for recent_lead in recent_leads %}
                    <a class="list-group-item" href="#">
                        <b>{{recent_lead.click_user_name}} </b> lead offer <b>{{recent_lead.offer_name}}(ID={{ recent_lead.offer_id }})</b> with IP <b>{{recent_lead.click_ip}}</b> - ClickID=<b>{{recent_lead.click_id}} | Time Click: {{recent_lead.click_time}} || PostbackId= {{recent_lead.lead_id}}</b>
                        <span class="pull-right text-muted small">
                            <em>{{recent_lead.lead_time}}</em>
                         </span>
                    </a>
                {% endfor %}
            </div>
            <!-- /.list-group -->
            <a class="btn btn-default btn-block" href="{% url 'core:offer_list' %}">View All Offers</a>
        </div>
        <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
</div>